- system/scripts/npcs/tir/alissa.cs
This includes the missing keywords, the updated greeting, etc.
> Updated Alissa

- system/scripts/npcs/tir/alissa.cs
Forgot to check the wiki for any keywords.
> Added School Keyword to Alissa

- system/scripts/npcs/tir/bebhinn.cs
This updates includes...
• Updated greetings
• Missed keywords
• NPC shop
• Formatting fixes
> Updated Bebhinn

- system/scripts/npcs/tir/caitin.cs
- system/scripts/shops/grocery.cs
**Added**
• Missing Items from Shop
• Greetings
• Missing Keywords
**Updated**
• Grocery Shop + Formatting Fixes
• Other small formatting issues
**Removed**
• Gift tab from grocery.cs, since not all NPCs that have a grocery tab,
have a gift tab as well. (see Gelwyas)
> Updated Caitin & Grocery Shop

- system/scripts/npcs/tir/caitin.cs
Changed description and changed skill check method.
> Small Fixes in Caitin

- system/scripts/npcs/tir/deian.cs
• Added Repairs
• Fixed the shop
> Updated Deian

- src/ChannelServer/Skills/Combat/MagnumShot.cs
- src/ChannelServer/Skills/Combat/RangedAttack.cs
Bhafel Huntess does not get removed on skill use.
> Bhafel Huntress Arrow Exception

- src/ChannelServer/ChannelServer.csproj
- src/ChannelServer/Network/Handlers/Items.cs
- src/ChannelServer/Skills/Actions/DiceTossing.cs
- src/ChannelServer/Skills/Actions/ThrowDice.cs
- src/Mabi/Const/Effects.cs
Working Dice Tossing Skill.
Able to learn Dice tossing when Equipped.
Todo
Ammo Handling.
> Dice Tossing

- system/scripts/npcs/tir/dilys.cs
• Added Pet Healing
• Added missing shop
• Updated greetings
> Updated Dilys

- system/scripts/npcs/tir/duncan.cs
> Updated Duncan

- system/scripts/npcs/tir/malcolm.cs
> Malcolm's Shop

- src/ChannelServer/Scripting/Scripts/AiScript.cs
> AI reset aggro if target is warping

- system/scripts/npcs/tir/endelyon.cs
• Added Missing Keywords
• Added Upgrading
• Updated Keywords
> Updated Endelyon

- system/scripts/npcs/tir/ferghus.cs
> Updated Ferghus

- system/scripts/npcs/tir/goro.cs
Formatting and other small fixes
> Updated Goro

- system/scripts/npcs/tir/lassar.cs
• Added Repairing and Upgrading
• Added Missing Keywords
• Formatting fixes (I've been forgetting to use `<npcname/>`)
> Updated Lassar

- src/ChannelServer/Skills/Life/Refining.cs
> Fixed Refining Rank 6 skill traning

- system/scripts/npcs/sidhe/tarlach.cs
- system/scripts/npcs/sidhe/tarlach_bear.cs
- system/scripts/scripts_npcs.txt
Added both NPCs with their Keyword responses.
Missing: Spirit weapon and any other Quest related dialogues and options.
> Added Tarlach & Tarlach Bear NPCs

- system/scripts/npcs/tir/malcolm.cs
• Added greetings
• Added repairing
• Other small code fixes/updates
Github has a weird way of showing changes in the shop o.o
> Updated Malcom

- src/Shared/Database/AuraDb.cs
Fixed missing param declaration in the documentation
> Correct Documentation for Init

- system/scripts/ai/koboldbandit.cs
I know you wanted this.
Also dont look at me... this is official you know!
> Added losing clothes on Counter for Kobold Bandits.

- src/LoginServer/Database/Account.cs
- src/LoginServer/Network/Handlers/Creation.cs
- system/db/charcardsets.txt
Adds check for missing item sets when creating characters/partners.
Fixes #196.
> Fixed Character/Partner creation

- src/ChannelServer/Util/GmCommands.cs
* Supports targeting another player to close their session if they get stuck in a dialog.
> Modify HandleCloseNpc

- src/Shared/Database/AuraDb.cs
* Corrects doc for `Aura.Shared.AuraDb.SetAccountPassword(...)`
> Corrects documentation for SetAccountPassword

- src/LoginServer/LoginServer.cs
* Makes LoginServer.Server public for scripting (i.e. new packet handlers and such things)
> Makes LoginServer.Server public for scripting.

- src/ChannelServer/World/Entities/Creature.cs
- MagicAttackMod is now used in Magic Damage calculations
> MagicAttackMod influence on Magic Damage

- src/ChannelServer/Util/GmCommands.cs
* users target instead of sender
> Corrects Broadcast GmCommands to Have Desired Effect When Targeted

- src/ChannelServer/Network/Handlers/Items.cs
Introduced in b864baf4ce55add4865553972089285f2f6fe9b4
> Removed unnecessary static byte declaration

- system/scripts/npcs/tir/nora.cs
• Added greetings
• Added repairing
• Other small formatting fixes
> Updated Nora

- system/scripts/npcs/tir/piaras.cs
• Added greetings
The skills/campfire keywords seem to match. I tested them and got the results you see in the code. I guess that means it was changed not too long ago.
> Updated Piaras

- src/ChannelServer/Skills/Life/Campfire.cs
> Added 8th Anniversary Prop to the Campfire Skill

- src/ChannelServer/Network/Handlers/Props.cs
- src/ChannelServer/Skills/Combat/CombatMastery.cs
- src/ChannelServer/World/Entities/Creature.cs
* Refactor dual wielding flags from ``CombatMastery.cs`` to ``Creature.cs``
* Fixes wrong stun for prop hits while dual wielding.
* Include stamina consumption into ``Prop.cs``
> Fixes #251

- src/ChannelServer/Scripting/Scripts/GeneralScript.cs
Adding commands with descriptions was left out of GeneralScript, so here you go.
> Added GM command description support to GeneralScript

- sql/update_2016-04-08.sql
- src/ChannelServer/Database/ChannelDb.cs
- src/ChannelServer/Network/Sending/Helpers/CreatureHelper.cs
- src/ChannelServer/World/Entities/Creature.cs
- src/ChannelServer/World/Inventory/CreatureInventory.cs
> Decouples Creature Inventory size from RaceDB

- system/scripts/npcs/tir/ranald.cs
• Added Missing Keywords
• Added Upgrading
> Updated Ranald

- system/scripts/npcs/tir/trefor.cs
• Added greetings
• Added upgrading
• Added missing BGM
> Updated Trefor

- src/ChannelServer/Util/GmCommands.cs
for all that testing we devs do :)
> Added reloadscripts Alias

- src/ChannelServer/Scripting/Scripts/GeneralScript.cs
To make it easy for people to add their own aliases without modifying the source.
> Added AddAlias to General Scripts

- system/scripts/npcs/tir/nora.cs
> Fixed Nora's Repair Messages

- src/ChannelServer/Scripting/Scripts/NpcScript.cs
SetHoodDown will now work with armor/clothing that has hoods.
> Added an Armor Check for SetHoodDown

- system/scripts/npcs/tir/alissa.cs
- system/scripts/npcs/tir/bebhinn.cs
- system/scripts/npcs/tir/caitin.cs
This is the first batch of updated Tir NPCs. See a complete change list
for all NPCs below:
• added all greetings (ones that were missing)
• changed npc name to <npcname/> (except Deian)
> Tir NPC Batch 1

- system/scripts/npcs/dunbarton/aeira.cs
- system/scripts/npcs/dunbarton/aranwen.cs
- system/scripts/npcs/dunbarton/austeyn.cs
- system/scripts/npcs/dunbarton/eavan.cs
- system/scripts/npcs/dunbarton/glenis.cs
- system/scripts/npcs/dunbarton/kristell.cs
- system/scripts/npcs/dunbarton/manus.cs
- system/scripts/npcs/dunbarton/nerys.cs
- system/scripts/npcs/dunbarton/simon.cs
- system/scripts/npcs/dunbarton/stewart.cs
- system/scripts/npcs/dunbarton/walter.cs
- system/scripts/npcs/tir/alissa.cs
- system/scripts/npcs/tir/caitin.cs
- system/scripts/npcs/tir/deian.cs
- system/scripts/npcs/tir/dilys.cs
- system/scripts/npcs/tir/duncan.cs
- system/scripts/npcs/tir/endelyon.cs
- system/scripts/npcs/tir/ferghus.cs
- system/scripts/npcs/tir/goro.cs
- system/scripts/npcs/tir/lassar.cs
- system/scripts/npcs/tir/malcolm.cs
- system/scripts/npcs/tir/meven.cs
- system/scripts/npcs/tir/nora.cs
- system/scripts/npcs/tir/piaras.cs
- system/scripts/npcs/tir/ranald.cs
- system/scripts/npcs/tir/trefor.cs
I also added the greetings I already had to the NPCs that didn't have them yet.
> Updated All NPCs to the new Greet System

- system/scripts/npcs/bangor/bryce.cs
- system/scripts/npcs/bangor/comgan.cs
- system/scripts/npcs/bangor/edern.cs
- system/scripts/npcs/bangor/elen.cs
- system/scripts/npcs/bangor/gilmore.cs
- system/scripts/npcs/bangor/ibbie.cs
- system/scripts/npcs/bangor/jenifer.cs
- system/scripts/npcs/bangor/riocard.cs
- system/scripts/npcs/bangor/sion.cs
- system/scripts/npcs/gairech/seumas.cs
- system/scripts/npcs/sidhe/tarlach.cs
- system/scripts/npcs/sidhe/tarlach_bear.cs
- system/scripts/npcs/tir_na_nog/dougal.cs
mymemorysobad
Double checked, all is good.
> Updated Remaining NPCs to the new Greet System

- system/scripts/npcs/dunbarton/eavan.cs
- system/scripts/npcs/dunbarton/glenis.cs
- system/scripts/npcs/dunbarton/kristell.cs
The next batch of Dunbarton NPCs. See a list of changes below:
• added "who Saved the Goddess" (11001) response
• added missing phrases
• added missing default messages (in keywords)
• changed npc name to `<npcname/>`
Additionally, Kristell no longer says she's a restaurant owner :P #351
> Updated Eavan, Glenis, and Kristell

- system/scripts/npcs/dunbarton/manus.cs
- system/scripts/npcs/dunbarton/nerys.cs
The next batch of Dunbarton NPCs. See a list of changes below:
• added "who Saved the Goddess" (11001) response
• added missing phrases
• added missing default messages (in keywords)
• changed npc name to `<npcname/>`
> Updated Manus & Nerys

- src/ChannelServer/Skills/Life/Rest.cs
Making the Rest skill search for and use nearby sittable props.
> Sitting on props

- system/scripts/npcs/dunbarton/pero.cs
- system/scripts/scripts_npcs.txt
We forgot about this guy )':
Thanks to @xKamuna for translating his 3rd greeting message :)
> Added NPC Pero

- system/scripts/npcs/dunbarton/simon.cs
- system/scripts/npcs/dunbarton/stewart.cs
- system/scripts/npcs/dunbarton/walter.cs
The last batch of Dunbarton NPCs. See a list of changes below:
• added "who Saved the Goddess" (11001) response
• added missing phrases
• changed npc name to `<npcname/>`
• fixed some keywords being added
• other small fixes
> Updated Simon, Stewart, and Walter

- system/scripts/npcs/dugald/tracy.cs
• Added Upgrading
• Updated `@talk`
• Updated about_skill keyword
• Fixed ModifyRelation values
> Updated Tracy

- system/scripts/npcs/gairech/seumas.cs
• Added missing keywords (also reorganized some that were out of order)
• Updated Greetings
• Updated Default Messages
• Fixed ModifyRelation values
> Updated Seumas

- system/scripts/npcs/tir/ferghus.cs
- system/scripts/quests/ptj/blacksmith_ferghus.cs
- system/scripts/scripts_quests.txt
~~This commit contains dialogue only; no implemented PTJ QuestScripts.~~
Possible missing dialogue:
The ~~1 and~~ 3 star PTJ report response might not be possible to get, seeing as how Ferghus has only been giving out single-objective deliveries.
ref: #237 
TODO_ (Updated 27 Jul 2016)
* \(Separate PR) Provide quotes for talking while on the job for current other Tir NPCs.
> Add Ferghus PTJ

- system/scripts/npcs/bangor/bryce.cs
• Fixed intro for #241
• Added 11001 Title text
• Added missing Greetings
• Updated ModifyRelation values
Note: There'll be less updates from me now that college starts next week and I'm also working on another project.
> Updated Bryce

- system/scripts/npcs/bangor/comgan.cs
• Added title 11001
• Updated Greetings
• Updated ModifyRelation values
> Updated Comgan

- system/scripts/npcs/dunbarton/eavan.cs
- system/scripts/quests/ptj/adventurerassn_eavan.cs
- system/scripts/scripts_quests.txt
Taking a PTJ from Eavan is now possible but starting at intermediate-level jobs, there is a chance for you to run into the following:
Missing dialogue:
* first time worker PTJ inquiry
* first time accepting PTJ offer
* first time declining PTJ offer
* 1-star PTJ turn in response
* 3-star PTJ turn in response
Improvised dialogue:
* Item delivery: Tracy
* Extended item delivery: Manus -> Austeyn
* Extended item delivery: Nerys -> Simon
ref: #237
> Add Eavan PTJ

- system/scripts/npcs/dunbarton/aeira.cs
- system/scripts/quests/ptj/bookstore_aeira.cs
- system/scripts/scripts_quests.txt
Taking a PTJ from Aeira is now possible but starting at intermediate-level jobs, there is a chance to run into the following:
Missing dialogue:
* 1-star PTJ turn in response
* 3-star PTJ turn in response
Improvised dialogue:
* Extended item delivery: Nerys -> Stewart
* Extended item delivery: Manus -> Walter
> Add Aeira's PTJ

- system/scripts/npcs/bangor/edern.cs
• Added missing greetings
• Keyword updates
• ModifyRelation value updates
> Updated Edern

- system/scripts/npcs/dunbarton/nerys.cs
- system/scripts/quests/ptj/wepshop_nerys.cs
- system/scripts/scripts_quests.txt
> Add Nerys PTJ

- src/ChannelServer/Network/Handlers/Misc.cs
- src/ChannelServer/Network/Sending/Send.Misc.cs
Improved sending the "Failed to open the Dressing Room" packet.
It's based on actual denial from officials.
> Fix for unimplemented Dressing Room freezing client.

- system/scripts/npcs/bangor/elen.cs
• Updated Phrases
• Added 11001 Title
• Added missing Greetings
• Updated ModifyRelation values
• Updated `about_skill` keyword
• Fixed `skill_gathering` keyword (oops)
• Added missing default message
> Updated Elen

- system/scripts/npcs/dunbarton/simon.cs
- system/scripts/quests/collection/40022_deliver_10_leather_bandanas.cs
- system/scripts/quests/collection/40023_deliver_5_common_silk_weaving_gloves.cs
- system/scripts/quests/collection/40024_deliver_2_cores_healer_gloves.cs
- system/scripts/quests/collection/40025_deliver_1_mongos_hat.cs
- system/scripts/quests/ptj/clothing_simon.cs
- system/scripts/scripts_quests.txt
- In this PR
- Dialogue for the following PTJs have been improvised:
- Extended delivery (Aeira -> Eavan)
- Extended delivery (Walter -> Austeyn)
- Details for the following extra quests have been improvised:
- (id:40022) Deliver 10 Leather Bandanas
- (id:40023) Deliver 5 Common Silk Weaving Gloves
- (id:40024) Deliver 2 Cores' Healer Gloves
- (id:40025) Deliver 1 Mongo's Hat
- To be solved in a separate PR
- #402 Collection books unimplemented
ref: #237
> Add Simon PTJ, respective extra delivery quests

- system/scripts/npcs/bangor/gilmore.cs
• Added GiftWeights
• Added Upgrading
• Added missing Greetings
• Updated Personal Info
• Updated Modify Relation Values
• Added missing Keywords
> Updated Gilmore

- system/scripts/npcs/bangor/ibbie.cs
• Added missing greetings
• Keyword updates
• ModifyRelation value updates
> Updated Ibbie

- src/Mabi/ErinnTime.cs
Should have been changed along with f0d785772c15919970f2a0291b85ec6a7801a341
I was getting discounts today (Tuesday).
> Fix ErinnMonth starting at 0

- system/scripts/npcs/bangor/jenifer.cs
• Added Repairing
• Added missing greetings
• Keyword updates
• ModifyRelation value updates
> Updated Jenifer

- system/scripts/npcs/bangor/riocard.cs
• Changed npc name to <npcname/>
• Added missing greetings
• Keyword updates
• ModifyRelation value updates
> Updated Riocard

- system/scripts/npcs/tin.cs
• Updated Intro for #241 
• Added Greet
• Added Missing Keywords
• Added Gift Message
> Updated Tin

- system/scripts/npcs/bangor/elen.cs
- system/scripts/quests/collection/40020_bigorder_iron_ingots.cs
- system/scripts/quests/ptj/blacksmith_elen.cs
- system/scripts/scripts_quests.txt
* 1-star PTJ turn in response
* 3-star PTJ turn in response
ref: #237
> Add Elen PTJ, Big Order of Iron Ingots collection quest 

- system/scripts/npcs/bangor/comgan.cs
- system/scripts/quests/ptj/church_comgan.cs
- system/scripts/scripts_quests.txt
> (Testing Needed) Add Comgan PTJ

- system/scripts/npcs/bangor/sion.cs
- system/scripts/quests/collection/40012_bigorder_iron_ore.cs
- system/scripts/quests/ptj/stope_sion.cs
- system/scripts/scripts_quests.txt
> (Testing Needed) Add Sion PTJ, Big Order of Iron Ore collection quest

- system/scripts/quests/ptj/blacksmith_elen.cs
I- err- forgot to include this in my patch the other day. It causes the script to fail to compile. sorry ._.
> Elen PTJ: Fix syntax error: Non-matched parenthesis

- system/scripts/npcs/sidhe/tarlach.cs
• Added missing Phrases
• Updated Greetings
• Updated Modify Relation
> Updated Tarlach

- system/scripts/npcs/sidhe/tarlach_bear.cs
• Updated Intro for #241 
• Fixed Phrases
• Removed greeting since they're all the same
> Updated Tarlach Bear

- system/scripts/npcs/tir_na_nog/dougal.cs
• Fixed Intro for #241 
• Added title 11001
• Fixed/Updated Greetings
• Updated ModifyRelation values
> Updated Dougal

- system/scripts/npcs/tir/alissa.cs
...I forgot a phrase as well o.o
> Added Gift & Relation Messages to Alissa

- src/ChannelServer/Skills/Combat/Windmill.cs
Rank 8 windmill was missing training for getting boss kills. This fixes that issue.
> Fix training for rank 8 Windmill

- system/scripts/dungeons/g1rp_31_dunbarton_math_dungeon.cs
Like in the Mores RP, the dungeon should end after killing 3 Ghost Armors rather than needing to kill all 6 bosses.
> Update Shiela RP to end after killing 3 bosses

- system/scripts/ai/succubus.cs
Updated the MagicStack Attack and Prepares.
> Updated SuccubusAi

- system/scripts/npcs/tir/malcolm.cs
...along with some Phrase updates
> Added Gift Reaction Messages to Malcolm

- system/scripts/npcs/tir/meven.cs
Meven and his walls of text...
> Added Gift Reaction Messages to Meven

- src/ChannelServer/Scripting/Scripts/NpcScript.cs
- system/scripts/quests/ptj/blacksmith_edern.cs
(5b86004 follow-up)
Also, Happy Holidays to all~
> Edern PTJ: Adjusted player skill check

- system/scripts/regions/nekojima.cs
- system/scripts/scripts_regions.txt
Adds field spawns to the southern island in Nekojima.
> Added Nekojima Field Spawns

- system/scripts/npcs/ceo/aer.cs
Aer's Gift weights updated to official values.
> Update Aer gift weights

- system/scripts/quests/collection/1016_largeiceelemental.cs
- system/scripts/quests/collection/1017_largefireelemental.cs
- system/scripts/quests/collection/1018_largelightningelemental.cs
- system/scripts/scripts_quests.txt
Adds the three produce massive elemental quests.
> Added Produce Massive Elemental Quests

- system/scripts/npcs/dunbarton/stewart.cs
Adds the produce massive elemental quests to Stewart's Shop.
> Update Stewart's shop with elemental quests

- system/scripts/npcs/emain/nele.cs
- system/scripts/scripts_npcs.txt
> Added Nele

- system/scripts/npcs/emain/nele.cs
Adds Wind Instruments: Melodies of the Soul to nele's normal music book tab.
> Added missing book to Nele's shop tab

- system/scripts/npcs/nekojima/bastet.cs
- system/scripts/scripts_npcs.txt
Adds the General Shop npc, Bastet to Nekojima.
> Added Bastet

- system/scripts/npcs/nekojima/dagon.cs
- system/scripts/scripts_npcs.txt
Adds the grocery store NPC Dagon to Nekojima.
> Added Dagon

- system/scripts/scripts_others.txt
> Added Golden Ratman to scripts_others.txt

- system/scripts/npcs/tir/piaras.cs
Also un-duplicated the campfire skill keyword.
> Added Gift Reaction Messages to Piaras

- src/ChannelServer/Util/GmCommands.cs
- system/conf/commands.conf
This command sets equipment proficiency.
Came in handy when testing the Artisan upgrades.
> Added 'prof' Command
