src/ChannelServer/Skills/Hidden/Dye.cs
src/ChannelServer/Util/Configuration/Files/World.cs
system/conf/world/items.conf

Adds configuration in items.conf that disables inventory removal of dyes
upon use.

Added Unlimited Dyes Configuration Option

---

src/ChannelServer/Skills/Magic/Healing.cs

Stamina is not consumed if Healing is used on other players.
Fixes #66.

Corrected stamina consumption for Healing skill

---

src/ChannelServer/Network/Sending/Send.Messages.cs
src/Shared/Util/Extensions.cs

Mabi can only show 100 chars per message. System messages, like command
help (esp the output of go) can exceed 100 chars and are just cut off.
This commit adds a word-wrapping algorithm and changes system messages so
the message is first wrapped by 100 chars (Mabi's limit) and then sent in
multiple messages.
Before:
After:

Added system message text wrapping.

---

src/Shared/Scripting/ScriptManager.cs

The loading message is now a little clearer regarding what actually happened. Initialization gets its own section. This is twofold. First, script init errors won't woverwrite the progress bar, and second, since
loading and init are two separate concepts, this will help localize any error messages that show up.
Both messages use the slightly-smoother "past-tense-verb" form instead of the "done verb-infinitive". This is a minor point, but it's a little friendlier in terms of English.

Updated script loading messages.

---

system/scripts/npcs/tir/meven.cs

Just a small note, the following `GiveKeyword`'s weren't in the g13 official script. I didn't touch them in the file, but I thought it would be worth mentioning here.
```
case "rumor":
GiveKeyword("shop_misc");    // Not in official g13 script
GiveKeyword("shop_grocery"); // Not in official g13 script
GiveKeyword("shop_headman"); // Not in official g13 script
case "shop_healing":
GiveKeyword("temple"); // Not in official g13 script
case "shop_bookstore":
GiveKeyword("shop_misc");       // Not in official g13 script
GiveKeyword("skill_composing"); // Not in official g13 script
```

Updated Meven

---

README.md

This is a really small one-liner fix, the link to wiki page seemed to be
pointing to a nonexistent page, so fixed it to point GitHub Wiki Pages.

Fixed wiki link to point to GitHub Wiki Pages

---

src/ChannelServer/ChannelServer.cs
src/ChannelServer/Network/Sending/Send.Internal.cs

* ChannelStatus is calculated based off the comments for each
ChannelStatus enum.
* IsInMaintenance can be used to set the server to Maintenance easily since it
is something one might do in a script, the other states should happen
automatically.
// Questions
Should we hold the ChannelStatus as a property and allow changes that was with automatic updates on change? I think that would break the design of the PR but maybe it's better?

Improves ChannelStatus reporting

---

src/ChannelServer/Network/Handlers/LogInOut.cs
src/ChannelServer/World/Entities/NPC.cs
src/ChannelServer/World/EventManager.cs

The Connecting events will be needed at some point anyway.
Used "Creature" instead of "Player", because both primary and secondary characters receive that info.
That `NPC npcchar = character as NPC;` will make sense a bit later. Planning to use it to update any necessary info about secondary characters that are connecting.

Events for early login phases.

---

system/scripts/npcs/tir/deian.cs
system/scripts/npcs/tir/dilys.cs
system/scripts/npcs/tir/duncan.cs

The next batch of Tir NPC updates. See a complete change list below:
• changed npc name to `<npcname/>` (except Deian)

Updated Deian, Dilys, and Duncan

---

system/scripts/npcs/tir/endelyon.cs
system/scripts/npcs/tir/ferghus.cs
system/scripts/npcs/tir/goro.cs

The next batch of Tir NPC updates. See a complete change list below:
• changed npc name to `<npcname/>` (except Deian)

Updated Endelyon, Ferghus, and Goro

---

system/scripts/npcs/tir/lassar.cs
system/scripts/npcs/tir/malcolm.cs
system/scripts/npcs/tir/meven.cs

The next batch of Tir NPC updates. See a complete change list below:
• changed npc name to `<npcname/>` (except Deian)

Updated Lassar, Malcolm, and Meven

---

system/scripts/npcs/tir/nora.cs
system/scripts/npcs/tir/piaras.cs
system/scripts/npcs/tir/ranald.cs
system/scripts/npcs/tir/trefor.cs

The last batch of Tir NPC updates. See a complete change list below:
• changed npc name to `<npcname/>` (except Deian)
Side note: `<npcname/>` doesn't work with Notice

Updated Nora, Piaras, Ranald, and Trefor

---

system/scripts/npcs/dunbarton/aeira.cs
system/scripts/npcs/dunbarton/aranwen.cs
system/scripts/npcs/dunbarton/austeyn.cs

The next batch of NPCs, now in Dunbarton. See a list of changes below:
• added missing greetings
• added "who Saved the Goddess" (11001) response
• added missing phrases
• added missing default messages (in keywords)
• changed npc name to `<npcname/>`

Updated Aeira, Aranwen, and Austeyn

---

src/ChannelServer/Skills/Life/Rest.cs

Rest checks now slightly wider area, but looks for the closest prop to sit on.

Sitting on props - improvements

---

src/ChannelServer/Scripting/Scripts/QuestScript.cs
src/ChannelServer/World/EventManager.cs
src/ChannelServer/World/Quests/Objectives.cs
src/Mabi/Const/Quests.cs

Additional resource: [Sample/Test script (gist)](https://gist.github.com/valdeza/a6ea9e16d87b7c70b5b6300faca5ebcf)
Dependent: All production quest objectives (particularly PTJs asking you to tailor or weave something)
Since events `CreatureCreatedItem` and `CreatureProducedItem` share the quest objective type (same byte ID and packet data structure in NewQuest packets), they share the same event handler (`QuestScript.OnCreatureCreatedOrProducedItem()`).
Additional consideration prior to merging: 
Is [using string comparison](https://github.com/valdeza/aura/blob/5c57b9e02442901abc48017da9c99ccbdc7cb4eb/src/ChannelServer/Scripting/Scripts/QuestScript.cs#L978) to check if skill just used matches the target skill on the quest objective acceptable? 
I was thinking of defining another enum, but …

Implement QuestObjectiveCreate

---

src/ChannelServer/World/Entities/Item.cs

(Also applies to blacksmith manuals.)
Sample usage:
```csharp
// Apprentice Sewing Pattern - Mongo Traveler Suit (F), 40 uses
npc.Player.GiveItem(Item.CreatePattern(60600, 10107, 40));
```
re: https://github.com/aura-project/aura/pull/376/files#r74115977 
Is this what you meant, @exectails ?
> Data is the global data, by modifying it you modify the durability of all future items with that item id.
Durability is now modified through `Item.OptionInfo` . When I spawn additional patterns, default durability is untouched.

Add CreatePattern factory method on Item.cs

---

src/ChannelServer/Scripting/Scripts/QuestScript.cs
src/ChannelServer/World/Inventory/CreatureInventory.cs
src/ChannelServer/World/Inventory/InventoryPockets.cs

Collect quest objectives will no longer count production skill works in progress (e.g. half-finished tailored Cores' Healers Dress).
This was solved by adding checks for whether PRGRATE metadata exists on the item to be counted. The modified item counting functions now have an optional bool parametre to specify whether or not to perform PRGRATE checks (made optional to avoid needing to change all count function call sites).

Bug fix: Do not count WIP items for Collect quest objectives

---

system/scripts/npcs/dugald/tracy.cs
system/scripts/quests/collection/40005_bigorder_firewood.cs
system/scripts/quests/ptj/general_tracy.cs
system/scripts/quests/ptj/inn_piaras.cs
system/scripts/scripts_quests.txt

_Edit: Missing: Dialogue for a first-time worker accepting and rejecting Tracy's PTJ._
Big Order of Firewood is a possible reward for turning in an advanced level PTJ. However, quest details have been improvised since never in my life will I be eligible to do advanced PTJs.
Also, Piaras had incorrect quest IDs ([mabipcap](https://github.com/valdeza/aura/blob/resrch_ptj-dialogue/etc/ptj-dialogue/tir-chonaill/piaras%20ferghus%20malcolm%20%40gcscaglia.mabipcap.raw.txt)), causing quest ID conflicts. Fixed!
ref: #237

Add Tracy PTJ, Big Order of Firewood collection quest

---

system/scripts/npcs/dunbarton/kristell.cs
system/scripts/quests/ptj/church_kristell.cs
system/scripts/scripts_quests.txt

Both this and Endelyon's PTJ scripts share quest IDs for egg collecting (/5021[036]5/), so this script must load last. If, in the future, script loading were to become multithreaded, this might be a problem.
ref: #237

Add Kristell PTJ

---

system/scripts/npcs/dunbarton/manus.cs
system/scripts/quests/ptj/healer_manus.cs
system/scripts/scripts_quests.txt

Both this and Dilys's PTJ scripts share quest IDs for wool gathering (/5051[036]1/), so this script must load last. If, in the future, script loading were to become multithreaded, this might be a problem.
ref: #237

Add Manus's PTJ

---

src/ChannelServer/Scripting/Scripts/QuestScript.cs
src/ChannelServer/World/Entities/Creatures/CreatureQuests.cs
system/scripts/quests/ptj/library_stewart.cs

Quest objective order and types have been retained.
Last book to collect was skipped in this hotfix so as to avoid removing two books (if the player were to be holding onto two for some reason).

Implement quest OnComplete(), #414 Fix - Stewart PTJ: Remove lingering books on quest completion

---

src/ChannelServer/Database/ChannelDb.cs
src/ChannelServer/World/Inventory/BankInventory.cs
src/Shared/Database/PremiumServices.cs

Fixes #417 by deleting all items on the character being saved along with all items in the bank belonging to the account before saving the items.
This adds a CreatureId to the bank tab in order to reference it when saving the tab.

Save all bank items

---

src/ChannelServer/World/Entities/Creatures/CreatureTitles.cs

It was checking normal title, rather than the option title.

Fix removing option title "Speed" bonus

---

src/ChannelServer/Util/GmCommands.cs
system/scripts/quests/ptj/blacksmith_elen.cs
system/scripts/quests/ptj/church_comgan.cs
system/scripts/quests/ptj/stope_sion.cs

- Comgan, Elen PTJ: Removed extraneous blank message when accepting a quest for the first time.
- Sion PTJ: Properly implemented parametrised strings.
- Add Blacksmithing to 'allskills' command _(Accidentally left out?)_

Fixup: Bangor PTJs, Add Blacksmithing to 'allskills' command

---

system/scripts/npcs/bangor/edern.cs
system/scripts/quests/ptj/blacksmith_edern.cs
system/scripts/scripts_quests.txt

Special thing about this PTJ: you are given a job matching your Blacksmithing skill level. In some cases there will not be a PTJ for your skill and PTJ level, in which case the usual Basic-level fallback will happen.
I wasn't sure whether all possible things to smith are available at all PTJ levels or the higher ranked ones are only available to people above Basic PTJ level.
- Quest IDs unconfirmed
- The following dialogue is missing: 
- First-time worker inquiry
- First-time worker reject PTJ
- First-time worker accept PTJ

Add Edern PTJ
